import { Plus_Jakarta_Sans } from 'next/font/google'
import GlobalStyle from "../styles/global";

const Jakarta = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Teste Leadster',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={Jakarta.className}>
        <GlobalStyle/>
        {children}
        </body>
    </html>
  )
}
