
export const DataCards = [
      { id: 1, name: "Leadster - Aumente sua Geração de Leads", url:"https://www.youtube.com/embed/WTabj8UO-yc"},
      { id: 2, name: "Como Transformar o Blog da sua Empresa em um Canal de Vendas (Inbound Marketing)", url:"https://www.youtube.com/embed/WAX8tDU5Alg" },
      { id: 3, name: "Qual é a diferença entre Marketing Digital, Marketing Conversacional e Marketing no WhatsApp?", url:"https://www.youtube.com/embed/jmZv8kDH8fg" },
      { id: 4, name: "Como Criar um Chat Grátis em Menos de 10 Minutos com a Leadster", url: "https://www.youtube.com/embed/XIBdJjahUkM" },
      { id: 5, name: "Mídia Paga: O que Aprendemos Investindo 383 mil reais (Webinar completo)", url: "https://www.youtube.com/embed/tdZQHWht-ZI" },
      { id: 6, name: "Como aumentar a Geração de Leads Qualificados do seu Site", url:"https://www.youtube.com/embed/9L9ZkGX1p_k" },
      { id: 7, name: "Como sua Empresa pode se preparar para um futuro sem cookies?", url:"https://www.youtube.com/embed/SapejfZ5oSM" },
      { id: 8, name: "Conheça as principais plataformas de Marketing Digital", url:"https://www.youtube.com/embed/yju8RTdhHQ0" },
      { id: 9, name: "Como editar as perguntas do Chat da Leadster", url: "https://www.youtube.com/embed/zfGWvSdhVpc"},
      { id: 10, name: "Mídia Paga: O que Aprendemos Investindo 383 mil reais (Webinar completo)", url: "https://www.youtube.com/embed/tdZQHWht-ZI" },
      { id: 11, name: "Leadster - Aumente sua Geração de Leads", url:"https://www.youtube.com/embed/WTabj8UO-yc" },
      { id: 12, name: "Como Transformar o Blog da sua Empresa em um Canal de Vendas (Inbound Marketing)", url:"https://www.youtube.com/embed/WAX8tDU5Alg" },
      { id: 13, name: "Qual é a diferença entre Marketing Digital, Marketing Conversacional e Marketing no WhatsApp?", url:"https://www.youtube.com/embed/jmZv8kDH8fg" },
      { id: 14, name: "Como Criar um Chat Grátis em Menos de 10 Minutos com a Leadster", url: "https://www.youtube.com/embed/XIBdJjahUkM" },
      { id: 15, name: "Mídia Paga: O que Aprendemos Investindo 383 mil reais (Webinar completo)", url: "https://www.youtube.com/embed/tdZQHWht-ZI" },
      { id: 16, name: "Como aumentar a Geração de Leads Qualificados do seu Site", url:"https://www.youtube.com/embed/9L9ZkGX1p_k" },
      { id: 17, name: "Como sua Empresa pode se preparar para um futuro sem cookies?", url:"https://www.youtube.com/embed/SapejfZ5oSM" },
      { id: 18, name: "Conheça as principais plataformas de Marketing Digital", url:"https://www.youtube.com/embed/yju8RTdhHQ0" },
      { id: 19, name: "Como editar as perguntas do Chat da Leadster", url: "https://www.youtube.com/embed/zfGWvSdhVpc"},
      { id: 20, name: "Mídia Paga: O que Aprendemos Investindo 383 mil reais (Webinar completo)", url: "https://www.youtube.com/embed/tdZQHWht-ZI" },
    ]
