export const CardsItens = [
      { id: 1, name: "Leadster - Aumente sua Geração de Leads", url:"https://www.youtube.com/embed/watch?v=WTabj8UO-yc&t=1s" },
      { id: 2, name: "Como Transformar o Blog da sua Empresa em um Canal de Vendas (Inbound Marketing)", url:"https://www.youtube.com/embed/watch?v=WAX8tDU5Alg" },
      { id: 3, name: "Qual é a diferença entre Marketing Digital, Marketing Conversacional e Marketing no WhatsApp?", url:"https://www.youtube.com/embed/watch?v=jmZv8kDH8fg&list=PL_dirAhLkFrtHAc0agF5ejKWVSGnOw7vV&index=17" },
      { id: 4, name: "Como Criar um Chat Grátis em Menos de 10 Minutos com a Leadster", url: "https://www.youtube.com/embed/watch?v=XIBdJjahUkM" },
      { id: 5, name: "Mídia Paga: O que Aprendemos Investindo 383 mil reais (Webinar completo)", url: "https://www.youtube.com/embed/watch?v=tdZQHWht-ZI" },
      { id: 6, name: "Como aumentar a Geração de Leads Qualificados do seu Site", url:"https://www.youtube.com/embed/watch?v=9L9ZkGX1p_k" },
      { id: 7, name: "Como sua Empresa pode se preparar para um futuro sem cookies?", url:"https://www.youtube.com/embed/watch?v=SapejfZ5oSM" },
      { id: 8, name: "Conheça as principais plataformas de Marketing Digital", url:"https://www.youtube.com/embed/watch?v=yju8RTdhHQ0&list=PL_dirAhLkFrtHAc0agF5ejKWVSGnOw7vV&index=19" },
      { id: 9, name: "Como editar as perguntas do Chat da Leadster", url: "https://www.youtube.com/embed/watch?v=zfGWvSdhVpc"},
      { id: 10, name: "Mídia Paga: O que Aprendemos Investindo 383 mil reais (Webinar completo)", url: "https://www.youtube.com/embed/watch?v=tdZQHWht-ZI" },
      { id: 11, name: "Leadster - Aumente sua Geração de Leads", url:"https://www.youtube.com/embed/watch?v=WTabj8UO-yc&t=1s" },
      { id: 12, name: "Como Transformar o Blog da sua Empresa em um Canal de Vendas (Inbound Marketing)", url:"https://www.youtube.com/embed/WAX8tDU5Alg" },
      { id: 13, name: "Qual é a diferença entre Marketing Digital, Marketing Conversacional e Marketing no WhatsApp?", url:"https://www.youtube.com/embed/watch?v=jmZv8kDH8fg&list=PL_dirAhLkFrtHAc0agF5ejKWVSGnOw7vV&index=17" },
      { id: 14, name: "Como Criar um Chat Grátis em Menos de 10 Minutos com a Leadster", url: "https://www.youtube.com/embed/watch?v=XIBdJjahUkM" },
      { id: 15, name: "Mídia Paga: O que Aprendemos Investindo 383 mil reais (Webinar completo)", url: "https://www.youtube.com/embed/watch?v=tdZQHWht-ZI" },
      { id: 16, name: "Como aumentar a Geração de Leads Qualificados do seu Site", url:"https://www.youtube.com/embed/watch?v=9L9ZkGX1p_k" },
      { id: 17, name: "Como sua Empresa pode se preparar para um futuro sem cookies?", url:"https://www.youtube.com/embed/watch?v=SapejfZ5oSM" },
      { id: 18, name: "Conheça as principais plataformas de Marketing Digital", url:"https://www.youtube.com/embed/watch?v=yju8RTdhHQ0&list=PL_dirAhLkFrtHAc0agF5ejKWVSGnOw7vV&index=19" },
      { id: 19, name: "Como editar as perguntas do Chat da Leadster", url: "https://www.youtube.com/embed/watch?v=zfGWvSdhVpc"},
      { id: 20, name: "Mídia Paga: O que Aprendemos Investindo 383 mil reais (Webinar completo)", url: "https://www.youtube.com/embed/watch?v=tdZQHWht-ZI" },
    ]